# Generated by Django 3.2.8 on 2023-12-09 00:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pest_traps', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pests_number', models.IntegerField(verbose_name='Número de Pragas')),
                ('temperature', models.FloatField(verbose_name='Temperatura')),
                ('pressure', models.FloatField(verbose_name='Pressão Atmósferica')),
                ('date', models.DateTimeField(verbose_name='Data de Captura')),
                ('processed_img_path', models.ImageField(upload_to='processed_imgs/', verbose_name='Imagem Processada')),
                ('captured_img_path', models.ImageField(upload_to='captured_imgs/', verbose_name='Imagem Capturada')),
                ('pest_trap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pest_traps.pesttrap')),
            ],
            options={
                'verbose_name': 'Monitoramento',
            },
        ),
    ]
